# Generated by Django 4.2.4 on 2023-09-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('default', 'Default'), ('gear', 'Gear'), ('dollar', 'Dollar')], default='default', max_length=50)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
            ],
        ),
    ]
