# Generated by Django 4.2.4 on 2023-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitalocean_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
